subscription onPricePointCreated {
  pricePointCreated {
    pricePoint {
      id
      createdAt
      value
    }
  }
}

subscription onEventCreated {
  eventCreated {
    event {
      createdAt
      type
      pricePoint {
        value
      }
    }
  }
}

subscription onStateUpdated {
  stateUpdated {
    state {
      status
      entryPricePoint {
        value
      }
    }
  }
}

query getEvents($limit: Int!) {
  events(limit: $limit) {
    createdAt
    type
    pricePoint {
      value
    }
  }
}

query getState {
  state {
    status
    entryPricePoint {
      value
    }
  }
}

query getPricePoints($limit: Int!) {
  pricePoints(limit: $limit) {
    createdAt
    value
  }
}
