query getEvents($limit: Int!) {
  events(limit: $limit) {
    createdAt
    type
    pricePoint {
      value
    }
  }
}

query getState {
  state {
    status
    downwardCount
    entryPricePoint {
      value
    }
    lastDownwardPricePoint {
      value
    }
  }
}

query getPricePoints($limit: Int!) {
  pricePoints(limit: $limit) {
    createdAt
    value
  }
}

query getProfiles {
  profiles {
    id
    stopLimitPercentage
    reservePercentage
    maximumLossesPerDay
    tradeInput
  }
}

query getExits($limit: Int!) {
  exits(limit: $limit) {
    createdAt
    pricePoint {
      value
    }
    entry {
      value
      pricePoint {
        value
      }
    }
  }
}
