subscription onPricePointCreated {
  pricePointCreated {
    pricePoint {
      id
      createdAt
      value
    }
  }
}

query getEvents($limit: Int!) {
  events(limit: $limit) {
    createdAt
    type
    pricePoint {
      value
    }
  }
}
